site_name: AK Lab How-To
docs_dir: docs

theme:
  name: material
  logo: assets/favicon.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - navigation.tabs # put top-level pages in tabs
    - content.image.zoom
  palette:
    - scheme: bh-dark
      primary: custom
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
plugins:
  - search
  - glightbox  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:   # for LaTeX
      generic: true  
  - mdx_truly_sane_lists:
      nested_indent: 4
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# MARK: EXTRA
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - styles/brand.css

# Top-right repo link
repo_url: https://github.com/queezz/aklab-howto
repo_name: queezz/aklab-howto

# MARK: NAV
nav:
  - Home:
      - ğŸ§­ Overview: index.md
      - ğŸ§° Software & tools: other-tools.md

  - ğŸ’» Software:
      - âš™ï¸ Installation: software/installation-guide.md
      - ğŸ™ Git:
          - ğŸ“˜ Intro: software/git/intro.md
          - âœï¸ Commits: software/git/commits.md
          - ğŸ·ï¸ Versioning: software/git/versioning.md
      - ğŸ“¦ PyPackage: software/pypackage.md
      - ğŸ Virtual Environments: software/venv.md
      - Venv Troubles: software/venv-troubles.md
      - ğŸŒ Flask Server: software/pihti-vacuum.md
      - ğŸ¼ Poetry: software/poetry.md
      - ğŸ” Workflows: software/workflows.md

  - ğŸ› ï¸ Hardware:
      - Equipment:
          - ğŸ”¥ TIG Welder: hardware/equipment/tig-welder.md
      - ğŸ§© KiCad: hardware/KiCad.md
      - Control Unit:
          - â„¹ï¸ About: hardware/controlunit/control-unit.md
          - ğŸšï¸ Waveshare AD/DA: hardware/controlunit/high-precision-adda-board.md
          - ğŸ“Š Y-corp ADC: hardware/controlunit/y-corp-adc-board.md
      - Sensors:
          - WCS1800: hardware/sensors/wcs1800.md
          - ACS712: hardware/sensors/acs712.md
      - ğŸ§· RasPi Pinouts: hardware/RasPi-pinout.md
      - ğŸ”¬ Instruments: hardware/instruments.md
      - ğŸ¦º Safety: hardware/safety.md

  - ğŸ“ Seminar:
      - Echelle spectra: seminar/echelle-spectra.md
